# ============================================
# Configuration Travelia - Clés API
# ============================================

# --- SMTP Gmail ---
smtp.email=atravelia43@gmail.com
smtp.password=lodzzkbeewmbnkyd
smtp.host=smtp.gmail.com
smtp.port=587

# --- Face++ API ---
facepp.api_key=VOTRE_FACEPP_API_KEY
facepp.api_secret=VOTRE_FACEPP_API_SECRET
facepp.detect_url=https://api-us.faceplusplus.com/facepp/v3/detect
facepp.compare_url=https://api-us.faceplusplus.com/facepp/v3/compare

# --- Google OAuth 2.0 ---
google.client_id=58569161353-9rs8m5mrso7d6klv6oog6ob12nrbbn0q.apps.googleusercontent.com
google.client_secret=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
google.redirect_uri=http://localhost/
google.auth_url=https://accounts.google.com/o/oauth2/v2/auth
google.token_url=https://oauth2.googleapis.com/token
google.userinfo_url=https://www.googleapis.com/oauth2/v3/userinfo
